# Generated by Django 4.0.5 on 2022-07-02 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('modes', models.CharField(choices=[('continental', 'continental'), ('chinese', 'chinese'), ('indian', 'indian')], max_length=100)),
                ('preparation_time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderingApp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('nyp', 'Not Yet Placed'), ('preparing', 'preparing'), ('ac', 'Awaiting Confirmation'), ('rejected', 'Rejected')], default='nyp', max_length=250)),
                ('ordered_date', models.DateField(auto_now_add=True)),
                ('order_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='orderingApp.orderitem')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_order', to='orderingApp.table')),
            ],
        ),
    ]
